# Исправленное подключение к PostgreSQL
spring.datasource.url=jdbc:postgresql://smarthome-postgres:5432/smarthome
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8082

# Валидация схемы при запуске
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true